/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.reactivex.*;
import io.reactivex.disposables.CompositeDisposable;
import io.reactivex.subjects.AsyncSubject;
import io.reactivex.subjects.BehaviorSubject;
import io.reactivex.subjects.PublishSubject;
import io.reactivex.subjects.ReplaySubject;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AppTest {

    Logger log = LoggerFactory.getLogger(AppTest.class);

    public static CompositeDisposable disposables;

    @BeforeClass
    public static void setUp() {
        disposables = new CompositeDisposable();
    }

    @Test
    public void createObservable() {

        Observable<Integer> observable = Observable.create(subscriber -> {
            log.info("Started emitting");

            log.info("Emitting 1st");
            subscriber.onNext(1);

            log.info("Emitting 2nd");

            subscriber.onNext(2);

            subscriber.onComplete();
        });

        log.info("Subscribing");

        //Please remember we should dispose each observer that have in our code. For it reason, please use Disposable class
        disposables.add(observable.subscribe(
                val -> log.info("Subscriber received: {}", val),
                err -> log.error("Subscriber received error", err),
                () -> log.info("Subscriber got Completed event")));

    }

    @Test
    public void createFlowable() {

        Flowable<Integer> flowable = Flowable.create(subscriber -> {
            log.info("Started emitting");

            log.info("Emitting 1st");
            subscriber.onNext(1);

            log.info("Emitting 2nd");
            subscriber.onNext(2);

            subscriber.onComplete();
        }, BackpressureStrategy.BUFFER);

        log.info("Subscribing");

        disposables.add(flowable.subscribe(
                val -> log.info("Subscriber received: {}", val),
                err -> log.error("Subscriber received error", err),
                () -> log.info("Subscriber got Completed event")));
    }

    @Test
    public void createSingleObservable() {

        Single<String> singleObservable = Single.create(subscriber -> {
            log.info("Started emitting");

            subscriber.onSuccess("It was successful");
        });

        log.info("Subscribing");

        disposables.add(singleObservable.subscribe(s -> log.info(s), error -> log.error(error.getMessage())));
    }

    @Test
    public void createSingleObservableThrowException() {

        Single<String> singleObservable = Single.create(subscriber -> {
            log.info("Started emitting");

            int sum = 1 / 0;

            subscriber.onSuccess("It was successful");
        });

        log.info("Subscribing");

        disposables.add(singleObservable.subscribe(s -> log.info(s), error -> log.error(error.getMessage())));
    }

    @Test
    public void createMaybeObservable() {

        Maybe<Object> maybeObservable = Maybe.create(emitter -> {

            log.info("Started emitting");

            emitter.onSuccess("Success");

            //emitter.onComplete();
        });

        log.info("Subscribing");

        disposables.add(maybeObservable.subscribe(s -> log.info(s.toString()), error -> log.error(error.getMessage())));
    }

    @Test
    public void createObservableUsingJust() {

        Flowable<Object> flowable = Flowable.just(1, 5, 10, "AD.2", true);

        disposables.add(flowable.subscribe(
                val -> System.out.println("Subscriber received: " + val),
                error -> log.info(error.getMessage()),
                () -> log.info("Completed")));
    }

    @Test
    public void createObservableUsingRange() {
        Flowable<Integer> flowable = Flowable.range(1, 10);

        disposables.add(flowable.subscribe(
                val -> System.out.println(("Subscriber received: " + val))));
    }

    @Test
    public void createObservableUsingFromArray() {
        Flowable<String> flowable = Flowable.fromArray(new String[]{"red", "green", "blue", "black"});

        disposables.add(flowable.subscribe(
                val -> System.out.println("Subscriber received: " + val),
                error -> log.info(error.getMessage()),
                () -> log.info("Completed")));
    }

    @Test
    public void createObservableUsingPublishSubject() {

        PublishSubject<String> subject = PublishSubject.create();
        subject.onNext("Hello");
        disposables.add(subject.subscribe(System.out::println));
        subject.onNext("Gorillas");
        subject.onNext("You're learning");
        subject.onNext("about Rx");
    }

    @Test
    public void createObservableUsingReplaySubject() {

        ReplaySubject<String> s = ReplaySubject.create();
        s.onNext("Hello");
        disposables.add(s.subscribe(value -> System.out.println("Observer1 listened: "+ value)));
        s.onNext("Gorillas");
        s.onNext("You're learning");
        s.onNext("about Rx");
        disposables.add(s.subscribe(value -> System.out.println("Observer2 listened: "+ value)));
    }

    @Test
    public void createObservableUsingBehaviorSubject() {

        BehaviorSubject<Integer> s = BehaviorSubject.create();
        s.onNext(0);
        s.onNext(1);
        s.onNext(2);
        disposables.add(s.subscribe(v -> System.out.println("Observer1 listened: " + v)));
        s.onNext(3);
        disposables.add(s.subscribe(v -> System.out.println("Observer2 listened: " + v)));
    }

    @Test
    public void createObservableUsingAsyncSubject() {

        AsyncSubject<String> s = AsyncSubject.create();
        s.onNext("I'm");
        s.onNext("a subject kind");
        disposables.add(s.subscribe(v -> System.out.println("Observer listened: "+ v)));
        s.onNext("Async");
        s.onComplete();
    }

    @AfterClass
    public static void clean() {
        //Here we're disposing our observer, we're cleaning the resources useless in order to avoid memory leaks.
        disposables.dispose();
    }


}
